from django.db import models
import uuid

def generate_uuid():
    return str(uuid.uuid4())

class User(models.Model):
    username = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user_id = models.CharField(max_length=36, default=generate_uuid)  # UUID generated by callable

    def __str__(self):
        return self.username


class Post(models.Model):
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)  # Make user optional

    def __str__(self):
        return self.content[:50]
